Repository clue/phar-composer, pull requests merged in 2020-12, with the labels that each got.

#112 Use GitHub actions for continuous integration (CI)
  .github/workflows/ci.yml
  .travis.yml
  README.md
  tests/Phar/PackagerTest.php
Labels: maintenance

#113 Run unit tests on PHP 7.4 too in CI
  .github/workflows/ci.yml
Labels: easy pick, maintenance

#114 Support Composer 2.0
  .github/workflows/ci.yml
  src/Clue/PharComposer/Phar/PharComposer.php
  tests/Phar/PharComposerTest.php
  tests/fixtures/07-composer-v2/composer.json
  tests/fixtures/07-composer-v2/composer.lock
  tests/fixtures/07-composer-v2/vendor/autoload.php
  tests/fixtures/07-composer-v2/vendor/composer/ClassLoader.php
  tests/fixtures/07-composer-v2/vendor/composer/InstalledVersions.php
  tests/fixtures/07-composer-v2/vendor/composer/LICENSE
  tests/fixtures/07-composer-v2/vendor/composer/autoload_classmap.php
  tests/fixtures/07-composer-v2/vendor/composer/autoload_namespaces.php
  tests/fixtures/07-composer-v2/vendor/composer/autoload_psr4.php
  tests/fixtures/07-composer-v2/vendor/composer/autoload_real.php
  tests/fixtures/07-composer-v2/vendor/composer/autoload_static.php
  tests/fixtures/07-composer-v2/vendor/composer/installed.json
  tests/fixtures/07-composer-v2/vendor/composer/installed.php
Labels: new feature
