Repository clue/phar-composer, pull requests merged in 2021-12, with the labels that each got.

#117 Fix check for valid package URL
  src/Clue/PharComposer/Phar/Packager.php
  tests/Phar/PackagerTest.php
Labels: bug, new feature

#120 Drop `composer.lock` and instead lock PHP version when building phar
  .github/workflows/ci.yml
  .gitignore
  bin/build.php
  composer.json
  composer.lock
  tests/Command/SearchTest.php
Labels: maintenance

#121 Update test suite to support PHPUnit 9
  .github/workflows/ci.yml
  composer.json
  phpunit.xml.dist
  phpunit.xml.legacy
  tests/Command/BuildTest.php
  tests/Command/InstallTest.php
  tests/Command/SearchTest.php
  tests/LoggerTest.php
  tests/Phar/PackagerTest.php
  tests/Phar/PharComposerTest.php
  tests/Phar/TargetPharTest.php
  tests/bootstrap.php
Labels: maintenance

#122 Support Symfony 6 on PHP 8.0
  .github/workflows/ci.yml
  composer.json
  tests/install-as-dep/composer.json
Labels: new feature

#123 Support PHP 8.1 release
  .github/workflows/ci.yml
  bin/phar-composer
  phpunit.xml.dist
  src/Clue/PharComposer/Package/Bundle.php
  tests/Command/SearchTest.php
Labels: new feature

#124 Use PSR-4 autoloading
  bin/build.php
  composer.json
  src/App.php
  src/Box/Extract.min.php
  src/Box/Extract.php
  src/Box/StubGenerator.php
  src/Command/Build.php
  src/Command/Install.php
  src/Command/Search.php
  src/Logger.php
  src/Package/Bundle.php
  src/Package/Package.php
  src/Phar/Packager.php
  src/Phar/PharComposer.php
  src/Phar/TargetPhar.php
Labels: easy pick, maintenance

#125 Add `.gitattributes` to exclude dev files from exports
  .gitattributes
Labels: maintenance
